#!/bin/sh

# Exports

. vendor/candy/tools/colors

export Changelog=Changelog.txt

if [ -f $Changelog ];
then
	rm -f $Changelog
fi

touch $Changelog

# Print something to build output
echo ${bldppl}"Generating Changelog..."${txtrst}

echo "===== CANDYROMS CHANGE LOG =====" >> $Changelog;
echo >> $Changelog;

for i in $(seq 14);
do
export After_Date=`date --date="$i days ago" +%d-%b-%Y`
k=$(expr $i - 1)
	export Until_Date=`date --date="$k days ago" +%d-%b-%Y`

	# Line with after --- until was too long for a small ListView
	echo '🍬 '$Until_Date' 🍬' >> $Changelog;
    CURRENT_PATH="$(realpath `pwd`)"
    repo forall -c "GIT_LOG=\`git log --oneline --after=$After_Date --until=$Until_Date --abbrev-commit --abbrev=7 --pretty=format:\"%h %s [%an]\"\` ; if [ ! -z \"\$GIT_LOG\" ]; then printf '\n* '; realpath \`pwd\` | sed 's|^$CURRENT_PATH/||' ; echo \"\$GIT_LOG\"; fi" >> $Changelog
	echo >> $Changelog;
done

sed -i 's/project/   */g' $changelog

cp $Changelog $OUT/system/etc/
rm $Changelog
